### ISSUE TITLE
Lightbulb overwritten by errors in gutter. Can we have an option to have it float instead?

### ISSUE THREAD

**Issue by beauwilliams** [kosayoda/nvim-lightbulb#1]
Love this plugin! Noticed when setting it up that errors will take priority over the lightbulb. Was wondering if we can have best of both worlds and move the bulb out of the gutter?

Just thinking off top of my head here.. But would really like to see both if possible. Anyways, thanks!

**Comment by kosayoda** [comment]
I added what I think you meant by `have it float` as a feature, please check the latest master if it suits your needs.
![image](https://user-images.githubusercontent.com/41782385/106566276-11d4d900-656b-11eb-9406-c927c5164352.png)

It's turned off by default, so you'll have to enable it.
Therefore, you now have three options to avoid conflict with diagnostics:
1. Use `text` and `texthl` for the diagnostics sign and `numhl` for the lightbulb sign: 
![image](https://user-images.githubusercontent.com/41782385/106566820-ce2e9f00-656b-11eb-8cf0-995c64e79d8e.png)
2. Use `numhl` for the diagnostics sign and `text` + `texthl` for the lightbulb sign:
![image](https://user-images.githubusercontent.com/41782385/106566982-07ffa580-656c-11eb-8742-fcad502221cf.png)
3. Use whatever you want for the diagnostics sign and use the `float` feature for the lightbulb.

Let me know what you think!

**Comment by beauwilliams** [comment]
Fantastic 😀 This is exactly what I meant

Have tested and it works!! Thank you so much, this is a wonderful improvement to this plugin.

**Comment by mortezadadgar** [comment]
@kosayoda is there any way to avoid code actions being prioritized over errors in gutter, changing sign priority to 0 didn't change the behavior

**Comment by kosayoda** [comment]
> @kosayoda is there any way to avoid code actions being prioritized over errors in gutter, changing sign priority to 0 didn't change the behavior

Please [open a new issue](https://github.com/kosayoda/nvim-lightbulb/issues/new/choose) with your configuration, thanks.
