### ISSUE TITLE
What font to use for this nice lightbulb icon?

### ISSUE THREAD

**Issue by jclsn** [kosayoda/nvim-lightbulb#12]
I have tried Nerdfonts etc. The only font giving me a nice icon is the Noto font, but it is not nice for coding. Would be nice if you could link some working fonts!

**Comment by kosayoda** [comment]
Hello, the default lightbulb text set for this plugin is `U+1F4A1 ELECTRIC LIGHT BULB`, which should be supported by most emoji/emoticon fonts out there. In the GIF, the font used is [Noto Color Emoji](https://www.google.com/get/noto/help/emoji/).

Other emoji fonts out there are [Symbola](https://dn-works.com/ufas/), [OpenMoji](https://openmoji.org/), and [Twemoji](https://github.com/twitter/twemoji).

Alternatively, you can choose the text to use for the lightbulb through the configuration, so you can theoretically choose any text that a font supports.

For example, this lightbulb 
![image](https://user-images.githubusercontent.com/41782385/123499055-77367d00-d666-11eb-969a-9c014254e623.png)
is offered by the [Material Design Webfont](https://github.com/Templarian/MaterialDesign-Webfont), but is not the lightbulb emoji, rather `U+F1275` in the [Private Use Area](https://en.wikipedia.org/wiki/Private_Use_Areas).

**Comment by kosayoda** [comment]
> but it is not nice for coding

I also just noticed this, and would like to clarify that I am using two fonts in the example GIF. The text font is [Iosevka SS02](https://typeof.net/Iosevka/), while the emoji font is [Noto Color Emoji](https://www.google.com/get/noto/help/emoji/).

This is done by setting a [fallback font](https://wiki.archlinux.org/title/Fonts#Fallback_font_order) (link given is for most linux distributions), so you could look into setting that up to get a nice coding font while still having a nice icon font.

**Comment by coldspark29** [comment]
Thank you for the advice. I have already figured something out by using the Nerd Fonts tweaked fonts. The light bulb is not as nice as the Noto Emoji one, but they are good for coding.

I couldn't get it to work with the fallback font and also don't think it is a nice way getting the fonts to work. At least not a global fallback font. One for the terminal emulator would be alright.
