### ISSUE TITLE
Update LSP handler signature to work with Neovim master

### ISSUE THREAD

**Issue by polyzen** [kosayoda/nvim-lightbulb#15]
https://github.com/neovim/neovim/issues/14090#issuecomment-913198455

**Comment by kosayoda** [comment]
Thanks for the heads up! I've updated the handler in https://github.com/kosayoda/nvim-lightbulb/commit/7411586f6b431a9c49a50fa962b6d6eae25aeb20. Please pull the latest master and let me know if further issues arise.
