### ISSUE TITLE
Way to ignore certain lsps?

### ISSUE THREAD

**Issue by jandamm** [kosayoda/nvim-lightbulb#23]
I use null-ls to present gitsigns actions as code actions.
Is there a way to not show a lightbulb for those actions? I'd be fine with just ignoring null-ls completely. Wouldn't have to be on the per action level.

**Comment by kosayoda** [comment]
Currently not, but I'll implement this as a feature.

**Comment by kosayoda** [comment]
Please pull the latest master and let me know if the feature suits your needs.

**Comment by jandamm** [comment]
Thanks, this works as expected 👍
