### ISSUE TITLE
[deprecated] Use of deprecated api

### ISSUE THREAD

**Issue by kunzaatko** [kosayoda/nvim-lightbulb#24]
`vim.lsp.diagnostic.get_all()` is deprecated in 0.6 it should be replaced by `vim.diagnostic.get()` instead.

**Comment by kunzaatko** [comment]
You can assign it to me, but I will have time only in about 2 weeks.

**Comment by kunzaatko** [comment]
akinsho/bufferline.nvim#272

**Comment by kosayoda** [comment]
Unlike the other diagnostic utilities, `vim.lsp.diagnostic.get_line_diagnostics` isn't hard deprecated (no deprecation message): [Source](https://github.com/neovim/neovim/blob/c4d70dae802ef074aaf54bdcbbd5f73380f74a86/runtime/lua/vim/lsp/diagnostic.lua#L299)

```
--- Get the diagnostics by line
---
--- Marked private as this is used internally by the LSP subsystem, but
--- most users should instead prefer |vim.diagnostic.get()|.
---
```
As I replicate almost entirely the function calls performed by internal LSP subsystem when calling "get code action" manually, I don't see how I can use `vim.diagnostic.get` without essentially replicating the private methods used in the neovim codebase itself.

**Comment by kunzaatko** [comment]
Ok. I see. Well sorry for the false issue then.
