### ISSUE TITLE
[Question] What colorscheme is used in the demo GIF?

### ISSUE THREAD

**Issue by HumblePresent** [kosayoda/nvim-lightbulb#27]
Nice plugin! My question is in the title :)

**Comment by kosayoda** [comment]
It's my own colorscheme, which is not available to the public (yet?). I'll update here if I end up creating a proper repository for it.

Meanwhile, if you are interested in the colors, here are the ones in the screenshot:

- bg: `#26272b`
- fg: `#d0d1d5`
- red: `#f67b7d`
- blue: `#619eef`
- green: `#95be93`
- magenta: `#da9cd9`
- yellow: `#dfbb8b`
- orange: `#e7a88d`

**Comment by HumblePresent** [comment]
Thanks! Would be cool to see it as a fleshed out colorscheme.
