### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by WDayu** [kosayoda/nvim-lightbulb#29]
emmmm, I just want to know how to use this plugin like your gif. I have not see anything about your keybinds and other configure in readme file, so, what the hotkey you used in this gif, and what I should configure.

BTW, I'm a noob, may be this question is too low-level.

Thanks!

**Comment by rockyzhang24** [comment]
This plugin just marks where the code actions are available. Code actions themselves are provided by language servers. So you need [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) to setup the servers you need. In `nvim-lspconfig`, you can setup a keymap to list code actions. The popup window in gif showing all available code actions is from [telescope](https://github.com/nvim-telescope/telescope.nvim), which can accept anything and display them in a popup floating window.

**Comment by WDayu** [comment]
Thank you very much, it was really useful to solve my confusion
