### ISSUE TITLE
Cmp's Ghost text is overwritten

### ISSUE THREAD

**Issue by fgheng** [kosayoda/nvim-lightbulb#34]
I used [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) as the completetion framework and I opened its experiment feature 'ghost txt', but the bulb overwritten the ghost txt, how to avoid it?

![image](https://user-images.githubusercontent.com/50551377/166744323-a0bc7165-58ac-46f4-a1a6-a58aa99ed60d.png)

ghost txt is like as below
![image](https://user-images.githubusercontent.com/50551377/166744801-b124b987-3b0a-4284-8721-eaba5c63970b.png)

**Comment by kosayoda** [comment]
Hello! With the newest release, you can set the position of the virtual text with `virtual_text.pos`, with something like `right_align` it should get out of your way most of the time.
