### ISSUE TITLE
feat req: Don't show icon if there a diagnostic msg in the line

### ISSUE THREAD

**Issue by tami5** [kosayoda/nvim-lightbulb#4]
Hey @kosayoda awesome plugin, I never actually used lsp action before I used nvim-lightbulb so thanks a lot :heart: 

I've disabling virtual text to skip some messages and focus and I noticed that the nvim-lightbulb icon overwrite or hides the diagnostic error indication. 

It would be cool if somehow there's a condition of some sort that controls the showing of the icon and show it only if no errors are present in the current line. 

Thanks

**Comment by kosayoda** [comment]
Hello, the lightbulb sign takes a `priority` option. If the priority is lower than the one used by the diagnostics (which you can also configure), the diagnostics sign will be on top.

**Comment by tami5** [comment]
Oh that very nice !! thanks a lot.
