### ISSUE TITLE
Is it possible to disable the lightbulb for unfocused buffer?

### ISSUE THREAD

**Issue by fitrh** [kosayoda/nvim-lightbulb#42]
When splitting a window with different buffers, I want to see the lightbulb only in the current buffer.

I'm trying to use `WinLeave` and `BufLeave` events to call this function

```lua
require("nvim-lightbulb").update_lightbulb({
    virtual_text = { enabled = false },
})
```

But it doesn't work, is there a way to do so?

**Comment by ctrlplusb** [comment]
I'm also looking for a way to disable the lightbulb showing in my Nvim Tree panel.

**Comment by fitrh** [comment]
@ctrlplusb my workaround for this is putting this callback on `WinLeave` event

```lua
      local ns = vim.api.nvim_create_namespace("nvim-lightbulb")
      vim.api.nvim_buf_clear_namespace(args.buf, ns, 0, -1)
      require("nvim-lightbulb").update_lightbulb({
        virtual_text = { enabled = false },
      })
```

**Comment by kosayoda** [comment]
Hello! There are a few ways to solve this with the latest release.

1. Configure `ignore.ft` to the filetypes you wish to ignore (like `neo-tree`)
2. Set  `hide_in_unfocused_buffer = true` to stop showing a lightbulb on `WinLeave`

Please file another issue should you find a problem with the feature
