### ISSUE TITLE
Bug: Code Action shown, even when there is none available

### ISSUE THREAD

**Issue by chrisgrieser** [kosayoda/nvim-lightbulb#43]
<img width="964" alt="image" src="https://user-images.githubusercontent.com/73286100/201525532-e2153883-e3fb-4776-b53a-d1d7891cba77.png">

After the first time, the lightbulb is shown, it keeps on every appearing randomly at lines that do not even have a code action available. Tried with this minimal config:

```lua
require("nvim-lightbulb").setup {
	autocmd = {enabled = true},
}
vim.fn.sign_define("LightBulbSign", {text = "", texthl = "DiagnosticInfo", numhl = "", linehl = ""})
```

**Comment by kosayoda** [comment]
Hello, thanks for filing this issue.

I personally have noticed this before, but I can't reliably reproduce it. Do you have a piece of code + LSP that will reliably show an erroneous lightbulb? (does not have to be in the same place everytime, just that it does show up when it shouldn't) That would be very helpful.

**Comment by kosayoda** [comment]
Hello! Please file a new issue if this still happens with the latest release.
