### ISSUE TITLE
lightbulb_lsp_cancel, attempt to index local 'client' (a nil value)

### ISSUE THREAD

**Issue by AnoRebel** [kosayoda/nvim-lightbulb#53]
```sh
NVIM v0.9.2-dev-50+g0bc272d0e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Apologies for the title, I couldn't think of what to call this;
On every cursor move(due to the CursorHold(I) events), I get the error below, I'm not even sure where to debug, I couldn't find the nil client in the plugin source code, so I'm posting this here to atleast get another view...
I've encountered it in mostly Typescript/Javascript or Vue files

```sh
Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1981: attempt to index local 'client' (a nil value)
stack traceback:
	/usr/local/share/nvim/runtime/lua/vim/lsp.lua:1981: in function 'lightbulb_lsp_cancel'
	.../anonvim/lazy/nvim-lightbulb/lua/nvim-lightbulb/init.lua:243: in function <.../anonvim/lazy/nvim-lightbulb/lua/nvim-lightbulb/init.lua:204>
```

**Comment by kosayoda** [comment]
Hey! If it's consistently reproducible, can you let me know if the latest commit fixes this, or if it's happening even with the latest commit? The patch was 2 days ago.

**Comment by AnoRebel** [comment]
Sorry, I wasn't around my PC this weekend.
I just changed lazy to use master branch and it seems to be fixed now.
Thank you.

**Comment by kosayoda** [comment]
No worries!
