### ISSUE TITLE
get_active_clients is deprecated in nvim 0.10

### ISSUE THREAD

**Issue by seocamo** [kosayoda/nvim-lightbulb#65]
**NeoVim Version**
NVIM v0.11.0-dev-45+g879d17ea8
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

**Describe the bug**
get_active_clients is deprecated in version 0.10 and will be remove in 0.12, so it call notify and make popups.
the problem is on line 237 `for _, client in pairs(vim.lsp.get_active_clients({ bufnr = bufnr })) do`
 in init.lua

**have to fix**
replace vim.lsp.get_active_clients with `(nvim.lsp.get_clients or vim.lsp.get_active_clients)` with the () is important as it will pick the new get_clients if found ellers fall back on the old get_active_clients for old versions.

so the line should look like this `for _, client in pairs((nvim.lsp.get_clients or vim.lsp.get_active_clients)({ bufnr = bufnr })) do` for init.lua:237
and   `for _, client in pairs((nvim.lsp.get_clients or vim.lsp.get_active_clients)({ bufnr = bufnr })) do` for init.lua:346

thanks for a great plugin.

**Comment by aarondill** [comment]
#62 (and it's duplicate #64) is an already submitted patch to fix this. It seems that we're just waiting for the maintainer to merge it.

**Comment by kosayoda** [comment]
Thanks for the report and patience! These should be fixed now.
