### ISSUE TITLE
vim.lsp.diagnostic.get_line_diagnostics is deprecated.

### ISSUE THREAD

**Issue by aarondill** [kosayoda/nvim-lightbulb#66]
- WARNING vim.lsp.diagnostic.get_line_diagnostics is deprecated. Feature will be removed in Nvim 0.12
  - ADVICE:
    - use vim.diagnostic.get instead.
    - stack traceback:
        /<...>/nvim-lightbulb/lua/nvim-lightbulb/init.lua:262

**Comment by Tainted-Fool** [comment]
#69 and #67 seem to have fixed the issue - simply waiting for maintainer to merge

**Comment by kosayoda** [comment]
This should be resolved with #69. Thanks for the report!
