### ISSUE TITLE
Information: virtual text at any column got merged

### ISSUE THREAD

**Issue by weilbith** [kosayoda/nvim-lightbulb#7]
I thought this might be interesting for this plugin here: neovim/neovim#13952
Feel free to close the issue at any time.

**Comment by teto** [comment]
agreed, I would rather have the buld prepended to the diagnostic in virtualtext then as a sign for instance.

**Comment by kosayoda** [comment]
Thanks for for the feedback! I'll look into extmarks and how they differ from the current virtualtext feature, then get around to implementing it.

**Comment by kosayoda** [comment]
@teto Can you please check out the `virtual-text-column` branch and let me know what you think?

**Comment by kosayoda** [comment]
Hello! I've finally made use of this feature, so this is now possible in the latest release.
