### ISSUE TITLE
Just don't work in here.

### ISSUE THREAD

**Issue by hrqmonteiro** [kosayoda/nvim-lightbulb#8]
I have nightly neovim with all the LSP configs needed, and the lightbulb just won't appear, never..

**Comment by kosayoda** [comment]
Can you provide a minimal example of your configuration that does not work?

**Comment by hrqmonteiro** [comment]
2 months later, i tried again and it literally won't work for me.

I installed the plugin via packer.
I put the default config:

```
require'nvim-lightbulb'.update_lightbulb {
    sign = {
        enabled = true,
        -- Priority of the gutter sign
        priority = 10,
    },
    float = {
        enabled = true,
        -- Text to show in the popup float
        text = "💡",
        -- Available keys for window options:
        -- - height     of floating window
        -- - width      of floating window
        -- - wrap_at    character to wrap at for computing height
        -- - max_width  maximal width of floating window
        -- - max_height maximal height of floating window
        -- - pad_left   number of columns to pad contents at left
        -- - pad_right  number of columns to pad contents at right
        -- - pad_top    number of lines to pad contents at top
        -- - pad_bottom number of lines to pad contents at bottom
        -- - offset_x   x-axis offset of the floating window
        -- - offset_y   y-axis offset of the floating window
        -- - anchor     corner of float to place at the cursor (NW, NE, SW, SE)
        -- - winblend   transparency of the window (0-100)
        win_opts = {},
    },
    virtual_text = {
        enabled = false,
        -- Text to show at virtual text
        text = "💡",
    }
}
```

Just activated the float (but even without it doesn't work). It just LITERALLY NEVER appears to me the lightbulb. I tried many languages with many codeactions and the lightbulb just doesn't show.

**Comment by kosayoda** [comment]
Hello, I believe what you're missing is in the [**Usage** section of the README](https://github.com/kosayoda/nvim-lightbulb#usage).

Basically, you have to call the lightbulb function whenever you want to activate the lightbulb handler. The most common usecase is shown in the section, where an `autocmd` is used to run the function on `CursorHold`, which is when a key is not pressed for a certain `updatetime` (see: `:h CursorHold` and `:h updatetime`).

This is in the README:
```lua
vim.cmd [[autocmd CursorHold,CursorHoldI * lua require'nvim-lightbulb'.update_lightbulb()]]
```

If you have a custom configuration and want to avoid putting everything on the same line, you can do something like this:
```lua
vim.cmd [[ autocmd CursorHold,CursorHoldI * lua LightBulbFunction() ]]
LightBulbFunction = function()
    require'nvim-lightbulb'.update_lightbulb {
        sign = {
            enabled = true,
            -- Priority of the gutter sign
            priority = 10,
        },
        float = {
            enabled = true,
            -- Text to show in the popup float
            text = "💡",
        }
    }
end
```

> Also you don't explain in the readme which are the keys i have to press to show that window, for example. How does it work actually?

Code actions are a functionality of the builtin neovim LSP server, not this plugin. Therefore documentation related to code actions themselves are in neovim, see `:h vim.lsp.buf.code_action`. If you bind a key to call that function, then code actions will show up if there are any.

Specifically to the README, the code action window I use is from [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) (I mention this right below the GIF). This is *not* required to get code actions.

**Comment by hrqmonteiro** [comment]
> Hello, I believe what you're missing is in the [**Usage** section of the README](https://github.com/kosayoda/nvim-lightbulb#usage).
> 
> Basically, you have to call the lightbulb function whenever you want to activate the lightbulb handler. The most common usecase is shown in the section, where an `autocmd` is used to run the function on `CursorHold`, which is when a key is not pressed for a certain `updatetime` (see: `:h CursorHold` and `:h updatetime`).
> 
> This is in the README:
> 
> ```lua
> vim.cmd [[autocmd CursorHold,CursorHoldI * lua require'nvim-lightbulb'.update_lightbulb()]]
> ```
> 
> If you have a custom configuration and want to avoid putting everything on the same line, you can do something like this:
> 
> ```lua
> vim.cmd [[ autocmd CursorHold,CursorHoldI * lua LightBulbFunction() ]]
> LightBulbFunction = function()
>     require'nvim-lightbulb'.update_lightbulb {
>         sign = {
>             enabled = true,
>             -- Priority of the gutter sign
>             priority = 10,
>         },
>         float = {
>             enabled = true,
>             -- Text to show in the popup float
>             text = "💡",
>         }
>     }
> end
> ```
> 
> > Also you don't explain in the readme which are the keys i have to press to show that window, for example. How does it work actually?
> 
> Code actions are a functionality of the builtin neovim LSP server, not this plugin. Therefore documentation related to code actions themselves are in neovim, see `:h vim.lsp.buf.code_action`. If you bind a key to call that function, then code actions will show up if there are any.
> 
> Specifically to the README, the code action window I use is from [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) (I mention this right below the GIF). This is _not_ required to get code actions.

I actually already had quite understand that, but with the default configs in the readme, it just wouldn't show it to me.

I was able to make it work now using this config.

My only questions are: how to make it appear faster, it is taking too long:


https://user-images.githubusercontent.com/17055027/119128465-10d99180-ba0c-11eb-9bea-b37c0848b00a.mp4

I found people using it and it appears so fast for them, like this one i found on reddit:

![img](https://user-images.githubusercontent.com/41671631/110590664-0e102400-81b3-11eb-9b9d-a894537104bc.gif)

And also, i wasn't able to change the highlights of it.
I tried doing as you say on the readme:

`vim.api.nvim_command('highlight LightBulbVirtualText guifg=#e0af68')`

And it didn't worked. Tried these as well (and none worked):

```
vim.fn.sign_define('LightBulbSign', {
    text = "",
    texthl = "LspDiagnosticsInformation",
    linehl="LspDiagnosticsInformation",
    numhl="LspDiagnosticsInformation" }
)
```

And tried the one in VimScript as well

```
augroup HighlightOverride
  autocmd!
  au ColorScheme * highlight LightBulbFloatWin ctermfg= ctermbg= guifg= guibg=
  au ColorScheme * highlight LightBulbVirtualText ctermfg= ctermbg= guifg= guibg=
augroup END
```

**Comment by kosayoda** [comment]
> My only questions are: how to make it appear faster, it is taking too long

Like I mentioned earlier, `CursorHold` triggers after `updatetime` miliseconds, see `:help CursorHold` and `:help updatetime`. The default `updatetime` is 4 seconds, which is what you are experiencing. You can set it to be lower, and thus the lightbulb will show up quicker.

> And also, i wasn't able to change the highlights of it.
> I tried doing as you say on the readme:

You show three different examples of configuration, and in all three examples you configure different features.

The plugin has three ways to show a lightbulb:
1. Sign
2. Floating window
3. Virtual text

```lua
vim.fn.sign_define('LightBulbSign', {
    text = "",
    texthl = "LspDiagnosticsInformation",
    linehl="LspDiagnosticsInformation",
    numhl="LspDiagnosticsInformation" }
)
```
^ This above example, which you gave, is to configure the lightbulb **sign**. This should work, unless `LspDiagnosticsInformation` is not a valid highlight group. By the way, `LspDiagnosticsInformation` is **not** a default highlight group set by neovim, so if you did not create the highlight yourself it will not work. See `:help lsp-highlight-diagnostics` to see the *actual* highlights available through the built-in LSP.

```lua
vim.api.nvim_command('highlight LightBulbVirtualText guifg=#e0af68')
```
^ This above example, which you gave, is to configure the lightbulb **Virtual Text**. Notice the `LightBulbVirtualText` highlight that is configured.

```vim
augroup HighlightOverride
  autocmd!
  au ColorScheme * highlight LightBulbFloatWin ctermfg= ctermbg= guifg= guibg=
  au ColorScheme * highlight LightBulbVirtualText ctermfg= ctermbg= guifg= guibg=
augroup END
```
^ This above example, which you gave, is to configure *both* the lightbulb **Virtual Text** and the lightbulb **Floating Window**. See the two different lines for each feature. You are also supposed to set the colors you want for each feature, see `:help highlight-args` to see what `ctermfg`, `ctermbg` etc. mean.
